title: Portafolio
description: Portfolio ML + Hacking
subtitle: Álex Pasalamar Serrano
logo: /images/scuffy-logo.jpg
favicon: /images/scuffy-logo.jpg

sass:
  sass_dir: _sass
  style: compressed

minimal_mistakes_skin: "dark"
remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-include-cache

collections:
  projects:
    output: true
    sort_by: date
  writeups:
    output: true
    sort_by: date
